# fly.toml app configuration file generated for e-courtage-back on 2023-06-09T19:41:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "e-courtage-back"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
